export const ProductsListData = [
    {
        id: 1,
        url: 'https://bizweb.dktcdn.net/100/177/937/products/224573354-jpeg-670aaefd-8f3a-4665-978d-1b9e9fdb0d91-jpg-v-1635691900857.jpg?v=1698132424917',
        name: 'iPhone 13 mini',
        desc: 'This is iPhone 13 mini',
        type: 'iphone',
        capacity: '128 GB',
        price: '500$',
        image: "/images/13mini.jpeg",
    },
    {
        id: 2,
        url: 'https://cdn1.viettelstore.vn/Images/Product/ProductImage/1487195898.jpeg',
        name: 'iPhone 7 ',
        desc: 'This is iPhone 7',
        type: 'iphone',
        capacity: '32 GB',
        price: '120$',
        image: "/images/iphone7.jpeg",
    },
    {
        id: 3,
        url: 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/p/h/photo_2022-09-28_21-58-51_4_1_2_2.jpg',
        name: 'iPhone 14 Plus',
        desc: 'This is iPhone 14 Plus',
        type: 'iphone',
        capacity: '256 GB',
        price: '500$',
        image: "/images/14plus.jpeg",
    },
    {
        id: 4,
        url: 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/8/-/8-plus-3_6.png',
        name: 'iPhone 8 plus',
        desc: 'This is iPhone 8 plus',
        type: 'iphone',
        capacity: '64 GB',
        price: '220$',
        image: "/images/8plus.jpeg",
    },
    {
        id: 5,
        url: 'https://didongmoi.com.vn/upload/images/product/dien-thoai-iphone-12-mini-64gb-cu-tim.jpg',
        name: 'iPhone 12 mini',
        desc: 'This is iPhone 12 mini',
        type: 'iphone',
        capacity: '128 GB',
        price: '370$',
        image: "/images/12mini.jpeg",
    },
    {
        id: 6,
        url: 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-15-pro-max_5.png',
        name: 'iPhone 15 Pro Max',
        desc: 'This is iPhone 15 Pro Max',
        type: 'iphone',
        capacity: '512 GB',
        price: '1200$',
        image: "/images/15promax.jpeg",
    },
    {
        id: 7,
        url: 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone11-green-select-2019_2_1_2_2_3.png',
        name: 'iPhone 11',
        desc: 'This is iPhone 11',
        type: 'iphone',
        capacity: '64 GB',
        price: '350$',
        image: "/images/11.jpeg",
    },
    {
        id: 8,
        url: 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone_xr_256gb_1.jpg',
        name: 'iPhone XR',
        desc: 'This is iPhone XR',
        type: 'iphone',
        capacity: '64 GB',
        price: '230$',
        image: "/images/xr.jpeg",
    },
    {
        id: 9,
        url: 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-13-pro-max.png',
        name: 'iPhone 13 Pro Max',
        desc: 'This is iPhone 13 Pro Max',
        type: 'iphone',
        capacity: '256 GB',
        price: '859$',
        image: "/images/13promax.jpeg",
    },
    {
        id: 10,
        url: 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-14_1.png',
        name: 'iPhone 14',
        desc: 'This is iPhone 13',
        type: 'iphone',
        capacity: '128 GB',
        price: '600$',
        image: "/images/14.jpeg",
    },
    {
        id: 11,
        url: 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-15-plus-256gb_3.png',
        name: 'iPhone 15',
        desc: 'This is iPhone 15',
        type: 'iphone',
        capacity: '128 GB',
        price: '740$',
        image: "/images/15plus.jpeg",
    },
    {
        id: 12,
        url: 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-15-pro-max_4.png',
        name: 'iPhone 15 Pro',
        desc: 'This is iPhone 15 Pro',
        type: 'iphone',
        capacity: '256 GB',
        price: '999$',
        image: "/images/15pro.jpeg",
    },
]
